name: Auto Merge to Production and Deploy

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  merge_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Automatic Merge
      run: |
        git fetch --all
        git config user.name "Prom1s1ngYoung"
        git config user.email "yqin7516@gmail.com"
        git checkout production
        git merge main
        git push origin production
